board: sparkfun_pro_micro_rp2040       # Dein Board (RP2040-basierend, z.B. Pi Pico v1)
shield: none      # Kein spezielles Keyboard-Shield, da du eigenes Overlay nutzt

build:
  # Lege hier weitere Build-Optionen fest falls nötig, z.B. Debug, Release

  type: application
  name: keyboard_rp2040

  # Die Konfigurationsdateien mit deiner Keymap und anderen Einstellungen
  overlays:
    - config/boards/pico/pico.overlay  # Deine Overlay Datei mit Matrix und LEDs
    - config/keymaps/keyboard_rp2040.keymap  # Deine custom Keymap Datei

  # Die zentrale Konfigurationsdatei (deine .conf Datei),
  # welche board, shield, keymap etc. referenziert
  configuration:
    - config/keyboard_rp2040.conf